import type { Engineer } from "./types";

export const issue04Engineers: Engineer[] = [
  {
    slug: "jason-liu",
    name: "Jason Liu",
    handle: "jxnlco",
    title: "Developer Experience Engineer, Codex",
    company: "OpenAI",
    previous: [
      "Creator, Instructor",
      "Independent consultant (RAG / structured outputs)",
    ],
    tier: "lab",
    schoolIds: ["encode-judgment", "harness-loops", "own-the-context"],
    oneLiner:
      "The Instructor author now on OpenAI's Codex team, who treats agents as durable workstreams: a personal monorepo for memory, skills extracted from Slack, and goals that stop only when tests pass.",
    superBio: [
      "Jason Liu built Instructor, the Python library that made structured LLM outputs a Pydantic object instead of a regex. OpenAI later cited it among the inspirations for Structured Outputs. He then joined the Codex developer-experience team, which is the interesting part: the person who spent years arguing that production LLM apps should be typed workflows, not ReAct retry loops, now publishes how he actually runs Codex as a teammate.",
      "The AI Engineer workshop 'Setting Yourself Up for Success' is the method dump. Compaction so a thread can live for weeks. Voice memos and accessibility-tree appshots instead of another screenshot. A version-controlled personal monorepo the agent reads and writes — projects, people, reusable skills. Heartbeat automations that check Gmail and Slack while he is in a meeting and leave Chrome tabs staged for review. Skills are files, not plugins: 'write like me' was generated by asking Codex to read six months of Slack and email. 'Review my code like Charlie' was a year of one colleague's PR comments.",
      "He is explicit about the trust gradient. Pinned threads that report on a defined condition. Persistent goals only where completion is verifiable — 'migrate the backend from Python to Rust, ensure all unit tests pass' and let it iterate until coverage is real. Ultra Goal stores the goal and the plan in a file so a human can edit both. The model should write the prompt. The human decides the artifact: a new thread, a skill, a staged draft. Give it enough context to prepare useful work. Keep action and approval boundaries clear.",
    ],
    whyThisPerson:
      "Lab seat plus a stealable personal OS. Instructor is how you make an agent return a type. The Codex workshop is how you make one live in your actual week. Pair with Lauren (skills as culture) and Hamel (evals).",
    collabModel:
      "Durable threads, not disposable chats. Memory in a git repo. Skills from your own corpus. Goals with a stop condition the computer can check. Heartbeats do the prep; you approve the send. Prefer DAGs and typed workflows over retry-until-JSON-parses.",
    reasoningStyle:
      "Make the output inspectable by ordinary software. Then make the loop observable. Taste is which work product to ask for — skill vs thread vs HTML briefing — not which magic words to append.",
    coreLessons: [
      {
        title: "Agents are workstreams, not chats",
        insight:
          "A pinned thread that reports on a condition beats a new window every morning. Persistence is a feature you have to design: compaction, memory files, heartbeats.",
      },
      {
        title: "Extract skills from the people you already trust",
        insight:
          "Six months of your Slack is a style guide. A year of Charlie's review comments is a reviewer. The highest-leverage skills are internal, not marketplace.",
      },
      {
        title: "Goals need a machine-checkable done",
        insight:
          "Do not persist a goal you cannot verify. Tests, coverage, a file the human can edit. Let the model write the prompt; you write the stop condition.",
      },
      {
        title: "Typed outputs beat retry loops",
        insight:
          "Instructor's original bet still holds for agents: describe the object, validate it, fail loudly. A DAG you can patch is cheaper than a ReAct loop that burns two dollars parsing JSON.",
      },
    ],
    resources: [
      {
        name: "Setting Yourself Up for Success",
        kind: "talk",
        url: "https://www.youtube.com/watch?v=il1c1a2FufU",
        note: "AI Engineer workshop. Monorepo memory, compaction, heartbeats, Ultra Goal.",
      },
      {
        name: "Instructor",
        kind: "repo",
        url: "https://github.com/instructor-ai/instructor",
        note: "Structured outputs as Pydantic. The library behind the typed-agent stance.",
      },
      {
        name: "High Agency Pydantic > VC Backed Frameworks",
        kind: "talk",
        url: "https://www.latent.space/p/instructor",
        note: "Workflows and DAGs over ReAct retry loops.",
      },
    ],
    quotes: [
      {
        text: "Give the system enough context to prepare useful work, but keep action and approval boundaries clear.",
        source: "AI Engineer notes on Jason Liu's Codex workflow, 2026",
      },
      {
        text: "I generally always prefer to have the model write the goal or write the prompt itself.",
        source: "Setting Yourself Up for Success, AI Engineer workshop",
        url: "https://www.youtube.com/watch?v=il1c1a2FufU",
      },
    ],
    related: ["lauren-tan", "hamel-husain", "boris-cherny", "lee-robinson"],
    twitter: "https://x.com/jxnlco",
    website: "https://jxnl.co",
    github: "https://github.com/jxnl",
  },
  {
    slug: "eno-reyes",
    name: "Eno Reyes",
    handle: "EnoReyes",
    title: "Co-founder and CTO",
    company: "Factory",
    previous: [
      "Machine learning engineer, Hugging Face",
      "Microsoft",
      "CS, Princeton",
    ],
    tier: "lab",
    schoolIds: ["verify-or-do-not-ship", "harness-loops", "own-the-context"],
    oneLiner:
      "Factory's CTO: bringing on agents is hiring a hundred interns, so you instrument the codebase with validation signals until autonomy is a property of the repo, not a vibe in the chat.",
    superBio: [
      "Eno Reyes grew up in a San Francisco immigrant restaurant family, studied CS at Princeton, trained and deployed LLMs at Hugging Face, then co-founded Factory with Matan Grinberg after a LangChain hackathon. The product name is a tell. Droids are not a chatbot with extra steps. They are specialized cognitive architectures for each slice of the SDLC — review, docs, tests, incidents, code — because 'agent' still meant demoware when they incorporated as the San Francisco Droid Company.",
      "The Stack Overflow Q&A is the personal craft. A good harness is hundreds of little optimizations, not a secret. Context across eight-to-ten-hour runs, environment injection, tool-call discipline, model-agnostic so you do not vendor-lock the org to one LLM or one IDE. Autonomy maturity analysis: most companies are missing the compile/lint/test/doc/SAST signals that would let an intern-fleet work without a staff engineer in every PR. Droid can install the missing signals. Your opinion should be which linter, not whether the hundredth intern gets a human review.",
      "Missions (Factory, 2026) is the architecture that follows from that diagnosis. Agents are highly reactive to context, so a worker that just implemented the feature is the worst person to judge it. Fresh context per feature. Validation contract written before any feature list. Independent scrutiny validators and black-box user-testing validators. Deferred Context Engine so skill catalogs do not eat the window. Custom droids are markdown subagents with their own tools and models. Stanford-adjacent research they cite: volume of AI code does not predict acceleration. Code quality does. Great code in, great code out.",
    ],
    whyThisPerson:
      "The enterprise twin of Lauren's factory, with the missing piece made explicit: you cannot review a hundred interns, so the repo has to grow a nervous system. Pair with Zach Lloyd (KPIs) and Cristina (agent-legible code).",
    collabModel:
      "Specialized droids per SDLC stage. Validation contract first. Fresh workers, separate validators. Instrument the repo until green/red signals exist for the agent. Plug droids into GitHub Actions and cron. Human opinion on standards, not on every diff.",
    reasoningStyle:
      "Frame the SDLC as games with scores. Measure org velocity and churn, not autocomplete accept rate. Harness quality is industrial process. Pattern-matchers amplify whatever pattern the tree already has.",
    coreLessons: [
      {
        title: "Agents are a hundred interns, not one teammate",
        insight:
          "You cannot staff-review that. Autonomy is the density of automatic green/red signals in the repo. Install the missing ones before you scale the fleet.",
      },
      {
        title: "Code quality is the only predictor",
        insight:
          "Volume of AI code, agent penetration, power-user density — none of it. Quality of the existing tree predicts whether agents accelerate or decelerate the company.",
      },
      {
        title: "Implementer context is adversarial to evaluation",
        insight:
          "Missions: write the validation contract first, spawn fresh workers, judge with a different agent. Self-review is confirmation bias with a larger window.",
      },
      {
        title: "Harness engineering is hundreds of details",
        insight:
          "Context, tools, environment, model-agnostic adapters. There is no individual secret. There is an industrial process for noticing bad outcomes and encoding the fix.",
      },
    ],
    resources: [
      {
        name: "Code smells for AI agents",
        kind: "essay",
        url: "https://stackoverflow.blog/2026/02/04/code-smells-for-ai-agents-q-and-a-with-eno-reyes-of-factory/",
        note: "The interview. Steal the hundred-interns line and the quality-predictor claim.",
      },
      {
        name: "How Missions Work",
        kind: "essay",
        url: "https://factory.ai/news/missions-architecture",
        note: "Theo Luan for Factory. Validation contract, fresh workers, independent validators.",
      },
      {
        name: "Deferred Context Engine",
        kind: "essay",
        url: "https://factory.ai/news/deferred-context-engine",
        note: "Load skill and MCP schemas only when the task needs them.",
      },
      {
        name: "Custom Droids",
        kind: "docs",
        url: "https://factory.mintlify.app/cli/configuration/custom-droids",
        note: "Markdown subagents with tool and model policy. Encode the checklist once.",
      },
    ],
    quotes: [
      {
        text: "Bringing on agents isn't hiring another person. It's like hiring a hundred intern-level engineers. You can't code review a hundred engineers.",
        source: "Code smells for AI agents, Stack Overflow, Feb 2026",
        url: "https://stackoverflow.blog/2026/02/04/code-smells-for-ai-agents-q-and-a-with-eno-reyes-of-factory/",
      },
      {
        text: "The only signal was code quality. The higher-quality of the code base, the more the AI accelerated the organization.",
        source: "Code smells for AI agents, Stack Overflow, Feb 2026",
        url: "https://stackoverflow.blog/2026/02/04/code-smells-for-ai-agents-q-and-a-with-eno-reyes-of-factory/",
      },
    ],
    related: ["zach-lloyd", "cristina-poncela", "lauren-tan", "scott-wu"],
    twitter: "https://x.com/EnoReyes",
    website: "https://factory.ai",
  },
  {
    slug: "eugene-yan",
    name: "Eugene Yan",
    handle: "eugeneyan",
    title: "Member of Technical Staff",
    company: "Anthropic",
    previous: [
      "Principal Applied Scientist, Amazon",
      "Aiterate Labs",
      "ML Lead, UCARE.AI",
    ],
    location: "Seattle",
    tier: "lab",
    schoolIds: ["verify-or-do-not-ship", "encode-judgment"],
    oneLiner:
      "The applied-ML writer who turned 'look at the data' into a method: eval-driven development, human-aligned judges, and the warning that buying an LLM-as-judge will not save a process you refuse to run.",
    superBio: [
      "Eugene Yan spent a decade shipping recommender systems and LLM products at Amazon, wrote the most-cited public playbooks on applied LLMs (eugeneyan.com, applyingml.com, applied-llms.org), then joined Anthropic. He is not a coding-agent power-user thread. He is the person the agent-factory people eventually need when 'the tests passed' is no longer the same as 'the product is good.'",
      "'An LLM-as-Judge Won't Save The Product' is the 2025 essay that should sit next to every factory memo. Evals are the scientific method: look at the data, annotate failures, hypothesize, experiment, measure. Eval-driven development is TDD for AI features — write success criteria before the prompt. Start with 30–100 labeled examples. Align the automated judge to those labels. Run the harness on every config change. Human sampling never goes away. Automated evaluators amplify a review culture; they do not replace one.",
      "The unfashionable observation from his LinkedIn practice: once the eval-plus-experiment harness exists, teams love hill-climbing the number. Setting up that harness is the ambiguous work almost nobody wants. And the number can become a crutch for the last 20% of quality, the part that still requires looking at raw outputs. He and Hamel/Shreya are the same church. He is the parish that still works inside a lab that ships Claude.",
    ],
    whyThisPerson:
      "The verification school needs an applied-ML adult who has run this at Amazon scale and will say the judge is not the product. Required reading before you put pstack in CI.",
    collabModel:
      "Define evals before the feature. Label a small balanced set. Calibrate LLM-as-judge against humans. One-click run-and-eval on every prompt or retrieval change. Keep sampling raw outputs. Implicit product feedback is a first-class signal.",
    reasoningStyle:
      "Scientific method over tooling. Narrow the task until you can measure it. Prefer a 40-example expert set you actually look at over a generic leaderboard.",
    coreLessons: [
      {
        title: "Look at the data first",
        insight:
          "Failure modes are in the traces, not in the dashboard. Annotate successes and failures 50/50. That set is the eval. Everything else is decoration.",
      },
      {
        title: "Eval-driven development",
        insight:
          "Write success criteria before the prompt. Baseline, change one thing, re-run. If you cannot measure the delta, you are vibe-tuning.",
      },
      {
        title: "A judge will not save a missing process",
        insight:
          "Automated evaluators scale annotation. They cannot compensate for never sampling outputs or never reading user feedback. Discipline is the product.",
      },
    ],
    resources: [
      {
        name: "An LLM-as-Judge Won't Save The Product",
        kind: "essay",
        url: "https://eugeneyan.com/writing/eval-process/",
        note: "Primary method. Scientific method, EDD, why the tool is not the work.",
      },
      {
        name: "Building Blocks for LLM Systems",
        kind: "talk",
        url: "https://eugeneyan.com/speaking/ai-eng-summit/",
        note: "AI Engineer 2023 keynote. Start with 40 expert evals. Narrow the task.",
      },
      {
        name: "eugeneyan.com",
        kind: "essay",
        url: "https://eugeneyan.com",
        note: "The archive. RecSys, applied LLMs, evals. No thread-bait.",
      },
    ],
    quotes: [
      {
        text: "If teams don't apply the scientific method, practice eval-driven development, and monitor the system's output, buying or building yet another evaluation tool won't save the product.",
        source: "An LLM-as-Judge Won't Save The Product, Apr 2025",
        url: "https://eugeneyan.com/writing/eval-process/",
      },
    ],
    related: ["hamel-husain", "shreya-shankar", "chip-huyen", "boris-cherny"],
    twitter: "https://x.com/eugeneyan",
    website: "https://eugeneyan.com",
    github: "https://github.com/eugeneyan",
  },
  {
    slug: "peter-steinberger",
    name: "Peter Steinberger",
    handle: "steipete",
    title: "Founder; creator of OpenClaw",
    company: "Independent (ex-PSPDFKit)",
    previous: ["Founder, PSPDFKit"],
    tier: "hidden-gem",
    schoolIds: ["plan-then-oneshot", "own-the-context", "harness-loops"],
    oneLiner:
      "The PSPDFKit founder who writes 100% of his code with 3–8 Codex sessions in one folder, then published the anti-charade manifesto: just talk to it, close the loop, treat AGENTS.md as scar tissue.",
    superBio: [
      "Peter Steinberger built PSPDFKit into the PDF stack a generation of iOS apps paid for, stepped away, and came back into a world where agents write the code. He is loud on purpose. The Pragmatic Engineer interview headline — 'I ship code I don't read' — is a dare, not a method. The method is the October 2025 essay 'Just Talk To It,' written by hand, about a 300k-line TypeScript/React/Tauri/Expo system he runs mostly alone.",
      "Daily driver: Codex CLI, gpt-5-codex, three-to-eight sessions in a 3×3 terminal grid, usually the same working tree. He tried worktrees and always came back. Blast radius is the planning unit: many small bombs, or one Fat Man plus small ones, never several large ones that make atomic commits impossible. Agents commit their own files. If a run exceeds the felt duration, hit escape and ask for status. He under-specs UI on purpose and morphs the chaos. For tricky work he still discusses, sometimes parks a spec, sometimes sends it to GPT-5-Pro for a second opinion, then builds in the same context because re-fetching the tree is a ten-minute tax he no longer wants to pay.",
      "The contrapoints are the gem. CLI over MCP (gh vs 23k tokens of GitHub MCP). Separate panes over hidden subagents, because he wants to see the context he engineered. tmux instead of harness background-task theater. AGENTS.md is ~800 lines of organizational scar tissue the model wrote whenever something went wrong. Twenty percent of time is agent-run refactor days — jscpd, knip, eslint, dead API routes — because iterating fast then paying the debt is more fun than ceremony on every commit. Tests in the same context as the feature. Screenshots in half of prompts. 'Just talk to it' is the opposite of pstack maximalism, and it only works because he closes the loop: compiler, tests, chrome-devtools, a two-minute Vercel preview.",
    ],
    whyThisPerson:
      "The highest-density personal workflow dump in the set that is not a skills repo. Required contrapoint to encode-judgment: sometimes the scar tissue file plus a model that actually reads the tree is enough.",
    collabModel:
      "Parallel Codex in one folder. Human owns blast radius and when to abort. Discuss, then build in the same window. Agents git-commit atomically. Close the loop locally. Refactor in batches. Phone is a one-liner inbox, not a second office.",
    reasoningStyle:
      "Intuition over ceremony. Feel the duration and the file count. Prefer talking to planning modes. Distrust wrappers between you and the model company. Senior-engineer management skills, applied to processes that type.",
    coreLessons: [
      {
        title: "Just talk to it",
        insight:
          "If you need a 40-page skill to make the model behave, you may be working around a model that will not read the tree. Shorter prompts, more screenshots, a model that pushes back.",
      },
      {
        title: "Blast radius is the plan",
        insight:
          "Know how long it should take and how many files it should touch. Several large parallel bombs make history and rollback impossible. Abort early when the feeling is wrong.",
      },
      {
        title: "CLIs beat MCPs for context tax",
        insight:
          "The agent can read a help menu once. A GitHub MCP that costs 23k tokens every turn is a product checkbox. Pay that tax only to close a loop you cannot close with curl.",
      },
      {
        title: "AGENTS.md is scar tissue, not literature",
        insight:
          "When something fails, tell the model to write a concise note. You did not author the 800 lines. You accumulated them. Clean later. Honor often.",
      },
    ],
    resources: [
      {
        name: "Just Talk To It",
        kind: "essay",
        url: "https://steipete.me/posts/just-talk-to-it",
        note: "Primary source. Hand-written. Blast radius, Codex grid, scar tissue file.",
      },
      {
        name: "The creator of Clawd: I ship code I don't read",
        kind: "essay",
        url: "https://newsletter.pragmaticengineer.com/p/the-creator-of-clawd-i-ship-code",
        note: "Gergely Orosz interview. Close the loop. Plan hard, then let Codex disappear for 20 minutes.",
      },
      {
        name: "steipete.me",
        kind: "essay",
        url: "https://steipete.me",
        note: "The archive, including Optimal AI Workflow. Read the primary posts, not the clips.",
      },
    ],
    quotes: [
      {
        text: "Don't waste your time on stuff like RAG, subagents, Agents 2.0 or other things that are mostly just charade. Just talk to it.",
        source: "Just Talk To It, Oct 2025",
        url: "https://steipete.me/posts/just-talk-to-it",
      },
      {
        text: "My Agent file is currently ~800 lines long and feels like a collection of organizational scar tissue. I didn't write it, codex did.",
        source: "Just Talk To It, Oct 2025",
        url: "https://steipete.me/posts/just-talk-to-it",
      },
    ],
    related: ["thorsten-ball", "simon-willison", "jeremy-howard", "boris-cherny"],
    twitter: "https://x.com/steipete",
    website: "https://steipete.me",
    github: "https://github.com/steipete",
  },
];
